name: GitHub Actions Demo
on: [push]
jobs:
  PruebaMarket:
    runs-on: ubuntu-latest
    steps:
    - run: echo "no hace nada"
    - name: Setup Java JDK
      uses: actions/setup-java@v2.3.1
      with:
        javaversion: 1.8
    
